packages:
  - packages/vue-next
  - packages/react
  - packages/view
  - packages/svg
  - packages/vue
  - packages/react-native
  - packages/web-components
catalog:
  "@babel/core": ^7.20.12
  "@babel/runtime": "^7.16.5"
  "@babel/eslint-parser": ^7.12.16
  "@babel/plugin-transform-react-jsx": ^7.16.0
  "@babel/plugin-transform-runtime": ^7.16.4
  "@babel/preset-env": ^7.16.4
  "@babel/preset-react": ^7.16.0
  "@changesets/cli": ^2.29.7
  "@popperjs/core": ^2.11.0
  "@rollup/plugin-babel": ^5.3.0
  "@rollup/plugin-commonjs": ^20.0.0
  "@rollup/plugin-json": ^6.1.0
  "@rollup/plugin-node-resolve": ^13.0.4
  "@rollup/plugin-replace": ^3.0.0
  "@svgr/core": ^6.1.2
  "@svgr/plugin-prettier": ^8.1.0
  "@svgr/plugin-svgo": ^6.2.0
  "@typescript-eslint/eslint-plugin": ^4.20.0
  "@typescript-eslint/parser": ^4.20.0
  "@vue/babel-plugin-jsx": ^1.1.1
  "@vue/babel-preset-jsx": ^1.4.0
  "@vue/cli-plugin-babel": ~5.0.0
  "@vue/cli-plugin-eslint": ~5.0.0
  "@vue/cli-service": ~5.0.0
  "@vue/compiler-sfc": ^3.2.26
  camelcase: ^8.0.0
  classnames: ^2.2.6
  clsx: ^2.1.1
  concurrently: ^6.4.0
  core-js: ^3.8.3
  cross-env: ^10.0.0
  decamelize: ^5.0.0
  del: ^8.0.0
  esbuild: ^0.14.0
  eslint: "^7.23.0"
  eslint-config-airbnb-base: ^14.2.1
  eslint-plugin-import: ^2.25.2
  eslint-plugin-vue: ^8.0.3
  fs-extra: ^11.3.2
  gulp: ^4.0.2
  gulp-clone: ^2.0.1
  gulp-concat: ^2.6.1
  gulp-header: ^2.0.9
  gulp-iconfont: 10.0.3
  gulp-iconfont-css: ^3.0.0
  gulp-merge: ^0.1.1
  gulp-rename: ^2.1.0
  gulp-sourcemaps: ^3.0.0
  gulp-svg-sprite: ^2.0.0
  gulp-typescript: ^6.0.0-alpha.1
  husky: ^9.0.0
  jsdom: ^26.1.0
  less: ^4.1.2
  lint-staged: ^16.1.6
  lodash: ^4.17.21
  omi: ^7.6.17
  oslllo-svg-fixer: ^5.0.0
  path: ^0.12.7
  postcss: ^8.4.4
  raw-loader: ^4.0.2
  react-native-svg: ^13.9.0
  rimraf: ^6.0.1
  rollup: ^2.42.1
  rollup-plugin-copy: ^3.5.0
  rollup-plugin-esbuild: ^4.7.2
  rollup-plugin-ignore-import: ^1.3.2
  rollup-plugin-less: ^1.1.3
  rollup-plugin-multi-input: ^1.3.1
  rollup-plugin-postcss: ^4.0.2
  rollup-plugin-static-import: ^0.1.1
  rollup-plugin-styles: ^3.14.1
  rollup-plugin-terser: ^7.0.2
  rollup-plugin-vue: ^6.0.0
  svg-parser: ^2.0.4
  svgo: ^4.0.0
  tailwind-merge: ^2.3.0
  ts-node: ^10.9.2
  tslib: ^2.1.0
  typescript: ^5.7.3
  vue-loader: ^17.0.0
  vue-template-compiler: 2.7.14
  xmldom: ^0.6.0
catalogs:
  vue26:
    "vue": "~2.6.12"
  vue27:
    "vue": "2.7.14"
  vue:
    "vue": "^3.5.21"
  react:
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
  tdesign:
    "tdesign-vue": "1.13.1-naruto"
    "tdesign-icons-vue": "^0.4.0"
  types:
    "@types/fs-extra": ^11.0.4
    "@types/gulp": ^4.0.17
    "@types/gulp-concat": ^0.0.37
    "@types/gulp-rename": ^2.0.6
    "@types/gulp-sourcemaps": ^0.0.38
    "@types/gulp-svg-sprite": ^1.2.36
    "@types/node": ^22.10.2
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
    "@types/svg-parser": ^2.0.6
    "@types/through2": ^2.0.41
