// 特殊的图标，需要用描边方式处理填充
export const specifiedIcons = [
  'caret-up-small',
  'caret-down-small',
  'caret-left-small',
  'caret-right-small',
  'drag-drop',
  'expand-down',
  'expand-up',
  'loading',
  'logo-alipay',
  'logo-behance',
  'logo-cnb',
  'logo-ie',
  'logo-stackblitz',
  'logo-wechat-stroke',
  'logo-wechatpay',
  'logo-wecom',
  'pause',
  'pause-circle',
  'play',
  'play-circle',
  'stop',
  'stop-circle',
];
