name: tdesign_icons
description: "TDesign Icons"
version: 0.0.1
homepage: https://tdesign.tencent.com/icons
repository: https://github.com/Tencent/tdesign-icons/tree/develop/packages/flutter
issue_tracker: https://github.com/Tencent/tdesign-icons/issues
publish_to: https://pub.dev
topics:
  - assets
  - icons
  - tdesign
  - symbol

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  code_builder: ^4.11.1
  dart_style: ^3.1.2

flutter:
   fonts:
     - family: TDIcons
       fonts:
         - asset: fonts/t.ttf
