name: auto-pr-tdesign-vue-next

on:
  pull_request:
    branches: [develop]
    types: [closed]
    paths:
      - "packages/vue-next/package.json"
jobs:
  auto-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: .node-version

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
      - name: Auto PR
        uses: TDesignOteam/tdesign-pr-trigger-action@develop
        with:
          pr_number: ${{ github.event.pull_request.number }}
          trigger: /pr-vue-next
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
