name: auto-release

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - run: pnpm install

      - run: pnpm run generate

      - uses: TDesignOteam/workflows/actions/setup-flutter@main
        with:
          flutter-version: 3.32.0

      - working-directory: ./packages/flutter
        run: |
          flutter pub get
          dart ./tool/generate.dart

          [ -f "lib/src/assets.g.dart" ] || (echo "❌ assets.g.dart 不存在" && exit 1)
          [ -f "fonts/t.ttf" ] || (echo "❌ t.ttf 不存在" && exit 1)
          flutter analyze

      - run: pnpm --filter "tdesign-icons-*" run --if-present build

      - uses: actions/setup-node@v7
        with:
          node-version: 24

      - uses: TDesignOteam/flow-pilot-action@develop
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          packages: "tdesign-icons-vue-next,tdesign-icons-react,tdesign-icons-view,tdesign-icons-svg,tdesign-icons-vue,tdesign-icons-web-components"
