name: auto-release-flutter

on:
  push:
    tags:
      - "tdesign_icons@*"

publish:
  permissions:
    id-token: write

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: TDesignOteam/workflows/actions/setup-flutter@main
        with:
          flutter-version: 3.32.0

      - name: install
        working-directory: ./packages/flutter
        run: flutter pub get

      - name: build
        working-directory: ./packages/flutter
        run: dart ./tool/generate.dart

      - name: publish
        working-directory: ./packages/flutter
        run: flutter pub publish --force
