name: auto-pr-tdesign-react

on:
  pull_request:
    branches: [develop]
    types: [closed]
    paths:
      - "packages/react/package.json"
jobs:
    auto-pr:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true 
        steps:
        - uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Auto PR tdesign-vue
          uses: TDesignOteam//tdesign-pr-trigger-action@develop
          with:
            pr_number: ${{ github.event.pull_request.number }}
            trigger: /pr-react
            token: ${{ secrets.TDESIGN_BOT_TOKEN }}