name: auto-pr

on:
  release:
    types: [created]

jobs:
  call-publish-tdesign-icons-view-tag:
    if: startsWith(github.event.release.tag_name,'tdesign-icons-view')
    runs-on: ubuntu-latest
    steps:
      - uses: TDesignOteam/workflows/.github/workflows/upgrade-deps.yml@main
        with:
          owner: Tencent
          repo: tdesign
          deps: tdesign-icons-view
          package-manager: pnpm
