name: Auto PR tdesign-miniprogram

on:
  pull_request:
    branches: [develop]
    types: [closed]
    paths:
      - "packages/vue/package.json"
jobs:
    pr-miniprogram:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true 
        steps:
        - uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: pr tdesign-miniprogram
          uses: TDesignOteam//tdesign-pr-trigger-action@develop
          env:
            GITHUB_TOKEN: ${{ secrets.TDESIGN_BOT_TOKEN }}
          with:
            pr_number: ${{ github.event.pull_request.number }}
            comment: /pr-miniprogram