name: MAIN_PULL_REQUEST

on:
  pull_request:
    branches: [develop, main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check_github_primary_email
        run: |
          # 获取最新提交的作者邮箱和提交者邮箱
          log_emails=$(git log --pretty=format:"%ae %ce" -1)
          # 如果邮箱包含 'tdesign@tencent.com'，跳过验证
          if [[ ${log_emails} =~ 'tdesign@tencent.com' ]];then 
              echo "$log_emails 跳过验证"
              exit 0
          fi
          # 如果邮箱包含 '@tencent.com'，校验失败，提示用户更改邮箱
          if [[ ${log_emails} =~ '@tencent.com' ]];then 
              echo "默认邮箱 $log_emails 校验非法，可以去 https://github.com/settings/emails 更改" 
              exit 2;
          else 
              # 否则，校验通过
              echo "邮箱 $log_emails 校验通过";
          fi

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: check_local_email
        run: |
          # 获取最新提交的作者邮箱和提交者邮箱
          log_emails=$(git log --pretty=format:"%ae %ce" -1)
          # 如果邮箱包含 'tdesign@tencent.com'，跳过验证
          if [[ ${log_emails} =~ 'tdesign@tencent.com' ]];then 
              echo "$log_emails 跳过验证"
              exit 0
          fi
          # 如果邮箱包含 '@tencent.com'，校验失败，提示用户更改本地邮箱
          if [[ ${log_emails} =~ '@tencent.com' ]];then 
              echo "本地提交邮箱 $log_emails 校验非法，需要本地更改重新提交" 
              exit 2;
          else 
              # 否则，校验通过
              echo "邮箱 $log_emails 校验通过";
          fi

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        icons:
          - tdesign-icons-vue
          - tdesign-icons-vue-next
          - tdesign-icons-react
          - tdesign-icons-svg
          - tdesign-icons-view
          - tdesign-icons-web-components

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run generate
      - run: pnpm run --filter ${{ matrix.icons }} build  
  
  site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm run generate

      - run: pnpm run --filter tdesign-icons-view build

      - run: mv packages/view/dist/demo.html packages/view/dist/index.html

      - run: mv packages/view/dist _site

      - run: zip -r _site.zip _site
      
      - name: upload _site artifact
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site.zip
          retention-days: 5

      - name: Save PR number
        if: always() 
        run: echo ${{ github.event.number }} > ./pr-id.txt

      - name: Upload PR number
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: ./pr-id.txt